version: 0.0
os: linux

files:
  - source: /
    destination: /appdir
    overwrite: yes

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 60
      runas: ubuntu

  ApplicationStart:
    - location: scripts/start.sh
      timeout: 120
      runas: ubuntu
