version: 0.0
os: linux
files:
  - source: /
    destination: /appdir

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 60
      runas: ubuntu

  AfterInstall:
    - location: scripts/start.sh
      timeout: 120
      runas: ubuntu
